<a href="https://colab.research.google.com/github/BDhivya-md3/day12/blob/main/day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Import the libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [4]:

#Import the dataset

dataset = pd.read_csv("/content/Social_Network_Ads.csv")

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)

print(y)


[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [5]:

#Splitting the dataset into trianing and test sets

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

print(x_train)
print(x_test)
print(y_train)
print(y_test)


[[    28  59000]
 [    41  72000]
 [    33  60000]
 [    25  79000]
 [    36 125000]
 [    32 117000]
 [    23  82000]
 [    51 134000]
 [    26  84000]
 [    37  80000]
 [    37  71000]
 [    39  75000]
 [    25  90000]
 [    21  88000]
 [    39 106000]
 [    32 117000]
 [    57  26000]
 [    40  57000]
 [    30  49000]
 [    24  89000]
 [    26 118000]
 [    38  65000]
 [    42  90000]
 [    40  47000]
 [    20  74000]
 [    52  38000]
 [    47  23000]
 [    53  82000]
 [    36  52000]
 [    40  78000]
 [    41  52000]
 [    47  34000]
 [    40 142000]
 [    28  89000]
 [    27  20000]
 [    33  51000]
 [    32 100000]
 [    49  39000]
 [    40  57000]
 [    35  77000]
 [    52  21000]
 [    26  16000]
 [    47  47000]
 [    40 107000]
 [    58  47000]
 [    26  80000]
 [    20  49000]
 [    45  22000]
 [    24  23000]
 [    35  50000]
 [    23  48000]
 [    41  59000]
 [    35  91000]
 [    48 134000]
 [    40  61000]
 [    26  35000]
 [    27  88000]
 [    24  55000]
 [    22  1800

In [6]:

#Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

print(x_train)
print(x_test)


[[-0.89546193 -0.33322999]
 [ 0.32904772  0.03850827]
 [-0.42449668 -0.30463474]
 [-1.17804108  0.23867502]
 [-0.14191753  1.55405655]
 [-0.51868973  1.32529454]
 [-1.36642718  0.32446078]
 [ 1.27097822  1.8114138 ]
 [-1.08384803  0.38165128]
 [-0.04772448  0.26727027]
 [-0.04772448  0.00991302]
 [ 0.14066162  0.12429402]
 [-1.17804108  0.55322278]
 [-1.55481328  0.49603228]
 [ 0.14066162  1.01074679]
 [-0.51868973  1.32529454]
 [ 1.83613653 -1.27687325]
 [ 0.23485467 -0.39042049]
 [-0.70707583 -0.61918249]
 [-1.27223413  0.52462753]
 [-1.08384803  1.35388979]
 [ 0.04646857 -0.16165848]
 [ 0.42324077  0.55322278]
 [ 0.23485467 -0.67637299]
 [-1.64900633  0.09569877]
 [ 1.36517127 -0.93373025]
 [ 0.89420602 -1.362659  ]
 [ 1.45936432  0.32446078]
 [-0.14191753 -0.53339674]
 [ 0.23485467  0.21007977]
 [ 0.32904772 -0.53339674]
 [ 0.89420602 -1.04811125]
 [ 0.23485467  2.04017581]
 [-0.89546193  0.52462753]
 [-0.98965498 -1.44844475]
 [-0.42449668 -0.56199199]
 [-0.51868973  0.83917528]
 

In [7]:
#implement KNN algorithm 
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 11,metric = 'minkowski')
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [8]:
#predict test set results 
y_pred = classifier.predict(x_test)


In [9]:
#get confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)

accuracy_score(y_pred, y_test)

[[62  3]
 [ 5 30]]


0.92

In [ ]:
#Visualizing Training set results

from matplotlib.colors import ListedColormap

x_set, y_set = sc.inverse_transform(x_train), y_train

x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min() - 0, stop = x_set[:, 0].max() + 0, step = 0.25),
                     np.arange(start = x_set[:, 1].min() - 0, stop = x_set[:, 1].max() + 1, step = 0.25))

plt.contourf(x1, x2, classifier.predict(sc.transform(np.array([x1.ravel(), x2.ravel()]).T)).reshape(x1.shape), cmap = ListedColormap(('red', 'green')))

plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())

for i, j in enumerate(np.unique(y_set)):
  plt.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1], c = ListedColormap(("red", "green"))(i), label = j)

plt.title("(training set")
plt.xlabel("Age")
plt.ylabel("Salary")
plt.legend()
plt.show()